### PR TITLE
Add unit test

### PR DESCRIPTION
**Pull request by dima-avdeev-jb**
Use runDesktopComposeUiTest with custom width and height.
And check result image

### CODE REVIEW

**Comment by ialokim** [comment]
Thanks a lot for that! I didn't manage to correctly import the whole repo into IntelliJ so I don't know how to run this. But if you've run it and it works, I'm happy to merge this!

**Comment by dima-avdeev-jb** [comment]
> Thanks a lot for that! I didn't manage to correctly import the whole repo into IntelliJ so I don't know how to run this. But if you've run it and it works, I'm happy to merge this!

Yeah, it works!
But first, let @igordmn check too

**Review by igordmn — APPROVED** [review]
Thanks!

**Comment by dima-avdeev-jb** [comment]
@ialokim Now, you can merge this PR

**Comment by ialokim** [comment]
Done. Thanks again!

**Pull request merged**
